### ISSUE TITLE
RetinaNet  plugin error

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#104] opened 2019-12-31 09:43 UTC
I update the system to TensorRT 7 , and run  your project. It will happen the error 
![image](https://user-images.githubusercontent.com/59388989/71617147-bd875900-2bf4-11ea-8392-8b8126a78b15.png)

it seems to the two file cause the error 
https://github.com/NVIDIA/retinanet-examples/tree/master/csrc/plugins

do you know why ?  thanks

**Comment by james-nvidia** [comment] 2019-12-31 21:57
We have not yet upgrade the project to TensorRT 7. We are working on it. Please use container `nvcr.io/nvidia/pytorch:19.09-py3` (which includes TensorRT 6) in the mean time.
We'll update this issue when we have updated the code.

**Comment by rbgreenway** [comment] 2020-01-05 05:09
Error trying to build the cppapi on a Jetson Xavier AGX with TensorRT 5.1.6. 
I followed these steps as given the the cppapi ReadMe file:
`
cd <path to cppapi directory inside the retinanet-examples repo>
mkdir build && cd build
cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++11" ..
make
`

It looks like, at a minimum, that the PluginFormat enum in NvInfer.h has changed.  Any ideas what the problem is?
Thanks!

output from make:
`In file included from /home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:31:0:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/DecodePlugin.h: In member function ‘virtual bool retinanet::DecodePlugin::supportsFormat(nvinfer1::DataType, nvinfer1::PluginFormat) const’:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/DecodePlugin.h:119:64: error: ‘kLINEAR’ is not a member of ‘nvinfer1::PluginFormat’
     return type == DataType::kFLOAT && format == PluginFormat::kLINEAR;
                                                                ^~~~~~~
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/DecodePlugin.h:27,
                 from /home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:31:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/DecodePlugin.h: In member function ‘virtual void retinanet::DecodePlugin::configureWithFormat(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, nvinfer1::DataType, nvinfer1::PluginFormat, int)’:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/DecodePlugin.h:124:84: error: ‘kLINEAR’ is not a member of ‘nvinfer1::PluginFormat’
 pe == nvinfer1::DataType::kFLOAT && format == nvinfer1::PluginFormat::kLINEAR);
                                                                       ^
In file included from /home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:32:0:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/NMSPlugin.h: In member function ‘virtual bool retinanet::NMSPlugin::supportsFormat(nvinfer1::DataType, nvinfer1::PluginFormat) const’:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/NMSPlugin.h:97:64: error: ‘kLINEAR’ is not a member of ‘nvinfer1::PluginFormat’
     return type == DataType::kFLOAT && format == PluginFormat::kLINEAR;
                                                                ^~~~~~~
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/NMSPlugin.h:28,
                 from /home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:32:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/NMSPlugin.h: In member function ‘virtual void retinanet::NMSPlugin::configureWithFormat(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, nvinfer1::DataType, nvinfer1::PluginFormat, int)’:
/home/bryan/retinanet-examples/retinanet-examples/csrc/plugins/NMSPlugin.h:102:84: error: ‘kLINEAR’ is not a member of ‘nvinfer1::PluginFormat’
 pe == nvinfer1::DataType::kFLOAT && format == nvinfer1::PluginFormat::kLINEAR);
                                                                       ^
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp: In constructor ‘retinanet::Engine::Engine(const char*, size_t, size_t, std::__cxx11::string, float, int, const std::vector<std::vector<float> >&, float, int, const std::vector<std::__cxx11::basic_string<char> >&, std::__cxx11::string, std::__cxx11::string, bool, size_t)’:
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:102:35: error: ‘class nvinfer1::IBuilder’ has no member named ‘createBuilderConfig’
     auto builderConfig = builder->createBuilderConfig();
                                   ^~~~~~~~~~~~~~~~~~~
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:105:45: error: ‘BuilderFlag’ has not been declared
     if(fp16 || int8) builderConfig->setFlag(BuilderFlag::kFP16);
                                             ^~~~~~~~~~~
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:110:52: error: ‘NetworkDefinitionCreationFlag’ has not been declared
     const auto flags = 0U << static_cast<uint32_t>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH);
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:111:29: error: ‘class nvinfer1::IBuilder’ has no member named ‘createNetworkV2’; did you mean ‘createNetwork’?
     auto network = builder->createNetworkV2(flags);
                             ^~~~~~~~~~~~~~~
                             createNetwork
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:120:32: error: ‘BuilderFlag’ has not been declared
         builderConfig->setFlag(BuilderFlag::kINT8);
                                ^~~~~~~~~~~
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:139:59: error: could not convert ‘{classOutput, boxOutput}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<nvinfer1::ITensor*>’
         vector<ITensor *> inputs = {classOutput, boxOutput};
                                                           ^
/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp:171:24: error: ‘class nvinfer1::IBuilder’ has no member named ‘buildEngineWithConfig’
     _engine = builder->buildEngineWithConfig(*network, *builderConfig);
                        ^~~~~~~~~~~~~~~~~~~~~
CMakeFiles/retinanet.dir/build.make:110: recipe for target 'CMakeFiles/retinanet.dir/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/home/bryan/retinanet-examples/retinanet-examples/csrc/engine.cpp.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/retinanet.dir/all' failed
make[1]: *** [CMakeFiles/retinanet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by yashnv** [comment] 2020-01-05 09:31
@rbgreenway. I suggest you use the TRT5 branch (TensorRT 5) or flash jetpack 4.3 which has TensorRT 6 and then use the main branch.

**Comment by DaveBGld** [comment] 2020-01-07 09:20
I solved this on TensorRT 6.0.1 adding this to the CMakeLists.txt

`set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --extended-lambda")`

**Comment by james-nvidia** [comment] 2020-01-15 18:09
Closing this issue as the TRT6 problem appears to have been solved. We are working on TRT 7 at the moment.

**Closed by james-nvidia** 2020-01-15 18:09 UTC
