### ISSUE TITLE
Tensor 606 is uniformly zero; network calibration failed

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#188] opened 2020-04-29 18:42 UTC
in nvcr.io/nvidia/pytorch:19.10-py3

build Calibration  in X86  GeForce GTX 1080 Ti 

Applying optimizations and building TRT CUDA engine...
Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 111) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 128) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 146) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 163) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 180) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 198) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 215) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 232) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 248) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 26) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 266) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 283) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 300) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 318) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 335) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 352) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 370) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 387) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 404) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 422) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 43) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 439) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 456) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 472) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 490) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 507) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 524) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 542) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 559) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 576) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 594) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 60) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 611) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 628) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 646) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 663) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 680) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 698) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 715) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 732) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 750) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 76) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 767) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 784) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 8) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 800) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 818) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 835) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 852) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 870) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 887) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 904) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 94) [Scale]_output is uniformly zero; network calibration failed.
Tensor 1004 is uniformly zero; network calibration failed.
Tensor 1019 is uniformly zero; network calibration failed.
Tensor 1033 is uniformly zero; network calibration failed.
Tensor 1047 is uniformly zero; network calibration failed.
Tensor 307 is uniformly zero; network calibration failed.
Tensor 322 is uniformly zero; network calibration failed.
Tensor 336 is uniformly zero; network calibration failed.
Tensor 350 is uniformly zero; network calibration failed.
Tensor 363 is uniformly zero; network calibration failed.
Tensor 378 is uniformly zero; network calibration failed.
Tensor 392 is uniformly zero; network calibration failed.
Tensor 406 is uniformly zero; network calibration failed.
Tensor 421 is uniformly zero; network calibration failed.
Tensor 435 is uniformly zero; network calibration failed.
Tensor 449 is uniformly zero; network calibration failed.
Tensor 464 is uniformly zero; network calibration failed.
Tensor 478 is uniformly zero; network calibration failed.
Tensor 492 is uniformly zero; network calibration failed.
Tensor 505 is uniformly zero; network calibration failed.
Tensor 520 is uniformly zero; network calibration failed.
Tensor 534 is uniformly zero; network calibration failed.
Tensor 548 is uniformly zero; network calibration failed.
Tensor 563 is uniformly zero; network calibration failed.
Tensor 577 is uniformly zero; network calibration failed.
Tensor 591 is uniformly zero; network calibration failed.
Tensor 606 is uniformly zero; network calibration failed.
Tensor 620 is uniformly zero; network calibration failed.
Tensor 634 is uniformly zero; network calibration failed.
Tensor 649 is uniformly zero; network calibration failed.
Tensor 663 is uniformly zero; network calibration failed.
Tensor 677 is uniformly zero; network calibration failed.
Tensor 690 is uniformly zero; network calibration failed.
Tensor 705 is uniformly zero; network calibration failed.
Tensor 719 is uniformly zero; network calibration failed.
Tensor 733 is uniformly zero; network calibration failed.
Tensor 748 is uniformly zero; network calibration failed.
Tensor 762 is uniformly zero; network calibration failed.
Tensor 776 is uniformly zero; network calibration failed.
Tensor 791 is uniformly zero; network calibration failed.
Tensor 805 is uniformly zero; network calibration failed.
Tensor 819 is uniformly zero; network calibration failed.
Tensor 834 is uniformly zero; network calibration failed.
Tensor 848 is uniformly zero; network calibration failed.
Tensor 862 is uniformly zero; network calibration failed.
Tensor 877 is uniformly zero; network calibration failed.
Tensor 891 is uniformly zero; network calibration failed.
Tensor 905 is uniformly zero; network calibration failed.
Tensor 920 is uniformly zero; network calibration failed.
Tensor 934 is uniformly zero; network calibration failed.
Tensor 948 is uniformly zero; network calibration failed.
Tensor 961 is uniformly zero; network calibration failed.
Tensor 976 is uniformly zero; network calibration failed.
Tensor 990 is uniformly zero; network calibration failed.
Writing to MAL_R50fpn_int8.plan...
root@667971367ba3:/workspace/dockerfold/retinanet-examples-mal_export#

**Comment by azuryl** [comment] 2020-04-29 19:05
but in 2080TI no this issue

**Comment by yashnv** [comment] 2020-04-30 22:10
What's the command you are using?

**Comment by azuryl** [comment] 2020-05-01 16:55
retinanet export retinanet_rn101fpn.pth  engine.plan --int8 --calibration-images /coco/images/val2017/

thank you

**Comment by yashnv** [comment] 2020-05-14 16:45
Hello have you resolved this error?

**Comment by yashnv** [comment] 2020-05-18 18:52
Closing this, appears to be resolved, please reopen if this persists.

**Closed by yashnv** 2020-05-18 18:52 UTC

**Comment by kunalgoyal9** [comment] 2020-06-28 13:47
same issue.... @yashnv Can you help me to solve this error?

**Comment by yashnv** [comment] 2020-06-28 16:14
@kunalgoyal9 where are you generating calibration cache? what container version? which branch? what's the GPU?

**Comment by kunalgoyal9** [comment] 2020-06-28 17:18
@yashnv Calibration cache in the same directory. I am using https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt this docker container, its onnx-tensorrt parser was not updated so I built from [git repo](https://github.com/onnx/onnx-tensorrt). I am using GTX 1080

**Comment by yashnv** [comment] 2020-06-28 17:28
Ah, GTX 1080 doesn't have native INT8 Tensor cores, that said, I generally don't recommend doing INT8 calibration on a 1080 because the performance gains are almost always negligible or worse than FP16.
I pushed some updates yesterday for 20.06 container that comes with updated TensorRT 7.1 and updated ONNX parsers, can you give that a try?

**Comment by kunalgoyal9** [comment] 2020-06-28 17:43
@yashnv I surely will give updated docker a try and will let you know. btw, is this error because of no int8 tensor cores on my GPU or something is wrong in the model?

**Comment by kunalgoyal9** [comment] 2020-07-01 16:06
@yashnv I have tried the updated docker and now I also change my GPU to T4 but still, I am getting that warning of uniformly zero. Also, my inference speed didn't improve for int8 quantizations.

**Comment by yashnv** [comment] 2020-07-01 16:12
Can you open a new issue with information about container used, steps you took to install this repo in the container, the output of nvidia-smi and the steps you took to produce this error. I think it will be helpful if we could reproduce this.
