### ISSUE TITLE
Network INT8 calibration failed.

### ISSUE THREAD

**Issue by Ricardozzf** [NVIDIA/retinanet-examples#3] opened 2019-03-27 04:05 UTC
Q1:
When I run command line `CUDA_VISIBLE_DEVICES=0 retinanet export retinanet_rn50fpn.pth model_int8.plan   --batch 2 --int8 --calibration-images /data/calib/ --calibration-batches 10 --calibration-table model_calibration_table --size 1280`, I got the following error log
```
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 1, anchors: 9
Exporting to ONNX...
Building INT8 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Tensor (Unnamed ITensor* 295) copy is uniformly zero; network calibration failed.
../builder/cudnnBuilder2.cpp (1508) - Misc Error in buildEngine: -1 (Could not find tensor x in tensorScales.)
../builder/cudnnBuilder2.cpp (1508) - Misc Error in buildEngine: -1 (Could not find tensor x in tensorScales.)
Segmentation fault (core dumped)
```
Q2:
Considering that tensorrt inference only occupies 1.6G cuda memory with batch 2, it's necessary to increase max batchsize of tensorrt engine. However, exporting trained pytorch model to tensorrt occupied too much cuda memory, and it's hard to increase max batchsize of tensorrt. Is there any solution?

**Comment by pkashinkunti** [comment] 2019-03-27 16:49
Hi Ricardozzf,

Q1: Can I ask which GPU you are trying to use? We have been able to successfully use the INT8 calibration process on Volta and Turing GPUs. I suspect your GPU may not have the proper HW support needed for fast INT8 (or FP16 according to the TRT error).

Q2: The issue you are describing is mostly likely happening during the PyTorch -> ONNX export before the TensorRT engine is built. We just added a small change to lower the GPU memory footprint during export, please give it a try and let us know if that helps you export models with a larger batch size.

Some other potential ideas: you could try using a smaller input resolution (you can add `--size x y` to your `retinanet export` command above to specify a different input resolution). Alternatively, TensorRT allows you to use create multiple execution contexts for a single TensorRT engine, which allows one set of weights to be reused for multiple inference tasks. You can get some more information here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#perform_inference_c

**Comment by Ricardozzf** [comment] 2019-03-28 04:54
Thanks for your reply @pkashinkunti:
Q1:
The GPU I used is TITAN X (Pascal), as far as I know, TITAN X do not support FP16, but it should support INT8. I have run FP32 tensorrt engine successfully.

Q2:
I am glad to inform that the small change did work. Now I could use TITAN X (Pascal) to generate tensorrt engines with a larger batch size` 2->12, 14, 16 ,32`. However, the  `*.plan` files whose batch size is bigger than `12` are unusable. The log shows:
```
root@ee13bae5e0e3:/workspace/retinanet/TensorRT# CUDA_VISIBLE_DEVICES=0 retinanet infer model_fp32_16.plan --images /data --annotations /data/Test.json --full-precision --batch 16
Loading CUDA engine from model_fp32_16.plan...
Preparing dataset...
    loader: pytorch
    resize: 800, max: 800
   backend: tensorrt
    device: 1 gpu
     batch: 16, precision: unknown
Running inference...
THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=265 error=77 : an illegal memory access was encountered
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 40, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in pin_memory_batch
    return batch.pin_memory()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at ../aten/src/THC/THCCachingHostAllocator.cpp:265
```
I have tried to use a smaller input resolution `800` with `16-batch plan file `, it did not work. But, I have run `12-batch plan file` with input resolution `1280` successfully.

**Comment by pkashinkunti** [comment] 2019-03-28 16:40
Q1: I just tried to use your command on a similar GPU (P40, which is also GP102 based like TitanX) and did not see the same failure. I used images from Pascal VOC2012 to calibrate the engine. Are you using a custom dataset for INT8 calibration? It may be the case that you need to use more batches for calibration (or perhaps a different dataset). 

Q2: Glad that change helped a bit: we are looking into this error with large batch plan files.

**Comment by florischabert** [comment] 2019-03-28 19:29
Regarding Q2, I merged https://github.com/NVIDIA/retinanet-examples/pull/7 which should fix the issue. Thanks for flagging it!

**Comment by Ricardozzf** [comment] 2019-03-29 10:29
Q2 has been fixed. :)
Regarding Q1, I have tried to use more batch and different dataset to calibrate model, but the error still exists. I find that someone has met similar issue [https://devtalk.nvidia.com/default/topic/1046066/int8-calibration-problem/](url), so I doubt that my model is the cause of Q1. I will tried it with a new model.

**Comment by Ricardozzf** [comment] 2019-04-03 01:51
I think I have found the cause of  the error. I trained a new model based on COCO2014 and successfully exported it to INT8-Plan, in this training, I used different dataset `custom dataset -> COCO2014` and class-num(`1->80`), so I doubt one of diferent dataset and different class-num caused this error.
If custom dataset is the cause, it may make `.pth` model generate some odd value that interrupted  TRT's optimizing, and if class-num is, perhaps some code segment contains variable class-num interrupted optimizing. 
For the above two cases, are there  any corresponding solutions?

**Comment by pkashinkunti** [comment] 2019-04-03 14:50
Would you mind listing the different steps/commands used in this process so we can better understand the issue and answer your questions?

**Comment by Ricardozzf** [comment] 2019-04-04 01:54
I used command `CUDA_VISIBLE_DEVICES=0,1,2,3 retinanet train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /coco/train --annotations /data/CocoTrain.json --val-images /coco/val --val-annotation /data/CocoVal.json  --batch 8 --logdir log --classes 80` which is different from `CUDA_VISIBLE_DEVICES=0,1,2,3 retinanet train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /data --annotations /data/SensingTrain.json --val-images /data --val-annotation /data/SensingTest.json --classes 1 --batch 8 --logdir log`

**Comment by florischabert** [comment] 2019-04-08 15:08
Is the loss converging in the second case? You might have to tweak the learning rate to get good results there.

**Comment by Ricardozzf** [comment] 2019-04-09 10:04
@florischabert Yes,the loss of the second case is convergent, and my model works correctly in fp32 mode. I have tried increase calibration-batches to **150**, replacing `Layer ReLU` with `Layer LeakyReLU`, and **changing calibration datasets**, but these did not work.

**Comment by florischabert** [comment] 2019-04-11 14:11
Hard to tell what the issue is with a specific dataset. You can try to calibrate using you test dataset and see if it works, maybe your calibration data is not a good representation of your test data?

**Comment by florischabert** [comment] 2019-04-16 17:32
Closing this, if you still have trouble with int8 please open a new issue with specific details allowing us to reproduce the problem. Thank you!

**Closed by florischabert** 2019-04-16 17:32 UTC

**Comment by shuangshuangguo** [comment] 2019-06-14 06:32
@Ricardozzf 
Hi, did you solve the problem? I have faced the same error. If you have solved, could you tell me more information about it? Thank you.
